baseURL = 'https://giaitoanoilong.netlify.app/'
languageCode = 'vi'
title = 'Giải Tỏa Nỗi Lòng'
theme = "mytheme"

[permalinks]
  post = "/:slug/"

[menu]
  [[menu.main]]
    name = "Trang chủ"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tâm sự cuộc sống"
    url = "/tamsu/"
    weight = 2
  [[menu.main]]
    name = "Đầu tư ít vốn"
    url = "/dautu/"
    weight = 3
  [[menu.main]]
    name = "Giới thiệu"
    url  = "/gioi-thieu/"
    weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]
