baseURL = 'https://giaitoanoilong.netlify.app/'
languageCode = 'vi'
title = 'Giải Tỏa Nỗi Lòng'

[permalinks]
  post = "/:slug/"

[params]
  description = "Blog chia sẻ tâm sự cuộc sống, đầu tư và góc nhìn thú vị."
  author = "Huy Cường"

[menu]
  [[menu.main]]
    name = "Trang chủ"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Tâm sự cuộc sống"
    url = "/tamsu/"
    weight = 2
  [[menu.main]]
    name = "Đầu tư ít vốn"
    url = "/dautu/"
    weight = 3
[[menu.main]]
    name = "Tarot"
    url = "/tarot/"
    weight = 4
  [[menu.main]]
    name = "Giới thiệu"
    url  = "/pages/giải-tỏa-nỗi-lòng--lắng-nghe-không-phán-xét-dịch-vụ-tâm-sự-giá-rẻ-cho-người-thu-nhập-thấp/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
